config/routes.rb
Rails.application.routes.draw do
  resources :assemblies
  resources :parts
  resources :accounts
  resources :books
  resources :suppliers
  resources :authors
  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :authors
    resources :suppliers
    resources :accounts
    resources :parts
    resources :assemblies
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :supplier
  has_and_belongs_to_many :assemblies
end

app/controllers/api/parts_controller.rb
module Api
  class PartsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_part
    def index
      @parts = Part.all
      render json: @parts
    end

    def show
      render json: @part
    end

    def create
      @part = Part.new(params_part)
      if @part.save
        render json: @part
      else
        render json: @part.errors, status: :unprocessable_entity
      end
    end

    def update
      if @part.update(params_part)
        render json: @part, except: %i[created_at]
      else
        render json: @part.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @part.destroy
      head :no_content
    end

    private

    def set_part
      @part = Part.find_by(id: params[:id])
    end

    def params_part
      params.require(:part).permit(:name, :price, :part_number, :supplier_id)
    end
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[show edit update destroy]
  before_action :set_supplier_id_options, only: %i[new show edit update destroy]

  def index
    @parts = Part.all
  end

  def show; end

  def new
    @part = Part.new
  end

  def edit; end

  def create
    @part = Part.new(part_params)
    if @part.save
      redirect_to part_url(@part), notice: 'Part was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @part.update(part_params)
      redirect_to part_url(@part), notice: 'Part was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @part.destroy
    redirect_to parts_url, notice: 'Part was successfully destroyed.'
  end

  private

  def set_supplier_id_options
    @supplier_id_options = Supplier.all.pluck(:name, :id)
  end

  def set_part
    @part = Part.find(params[:id])
  end

  def part_params
    params.require(:part).permit(:part_number, :supplier_id)
  end
end

app/helpers/api/parts_helper.rb
module Api::PartsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_with(model: part) do |form| %>
  <% if part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :part_number, style: "display: block" %>
    <%= form.text_field :part_number %>
  </div>

  <div class="field">
    <%= form.label :supplier_id, style: "display: block" %>
    <%= form.select("supplier_id", @supplier_id_options, include_blank: true) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<div id="<%= dom_id part %>">
  <p>
    <strong>Part number:</strong>
    <%= part.part_number %>
  </p>

  <p>
    <strong>Supplier:</strong>
    <%= part.supplier.name %>
  </p>

</div>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Show this part", @part %> |
  <%= link_to "Back to parts", parts_path %>
</div>

app/views/parts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parts</h1>

<div id="parts">
  <% @parts.each do |part| %>
    <%= render part %>
    <p>
      <%= link_to "Show this part", part %>
    </p>
  <% end %>
</div>

<p>
  <%= link_to "New part", new_part_path %>
</p>

<p>
  <%= link_to "Page home", root_path %>
</p>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to "Back to parts", parts_path %>
</div>

app/views/parts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @part %>

<div>
  <%= link_to "Edit this part", edit_part_path(@part) %> |
  <%= link_to "Back to parts", parts_path %>

  <%= button_to "Destroy this part", @part, method: :delete %>
</div>