config/routes.rb
Rails.application.routes.draw do
  resources :assemblies
  resources :parts
  resources :accounts
  resources :books
  resources :suppliers
  resources :authors
  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :authors
    resources :suppliers
    resources :accounts
    resources :parts
    resources :assemblies
  end
end

app/models/author.rb
require 'cpf_cnpj'

class Author < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :cpf, presence: true, uniqueness: true
  before_validation :cpf_is_valid?

  has_many :books

  private

  def cpf_is_valid?
    self.cpf = CPF.new(cpf, strict: false).formatted if cpf.present?
  end
end

app/controllers/api/authors_controller.rb
class Api::AuthorsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_author, only: %i[show update destroy]
  def index
    authors = Author.all
    render json: authors, except: %i[created_at updated_at]
  end

  def show; end

  def create
    @author = Author.new(author_params)
    if @author.save
      render json: @author, status: :created, except: %i[created_at updated_at]
    else
      render json: { errors: @author.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @author.update(author_params)
      render json: @author, except: %i[ created_at updated_at ]
    else
      render json: { errors: @author.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
    head :no_content
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :cpf)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  def index
    @authors = Author.all
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_url(@author), notice: "Author was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @author.update(author_params)
      redirect_to author_url(@author), notice: "Author was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
      redirect_to authors_url, notice: "Author was successfully destroyed."
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :cpf)
  end
end

app/helpers/api/author_helper.rb
# frozen_string_literal: true

module Api
  module AuthorHelper
  end
end

app/helpers/api/authors_helper.rb
# frozen_string_literal: true

module Api
  module AuthorsHelper
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= author.cpf %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<p>
  <%= link_to "New author", new_author_path %>
</p>

<p>
  <%= link_to "Page home", root_path %>
</p>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>