config/routes.rb
Rails.application.routes.draw do
  resources :assemblies
  resources :parts
  resources :accounts
  resources :books
  resources :suppliers
  resources :authors
  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :authors
    resources :suppliers
    resources :accounts
    resources :parts
    resources :assemblies
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :supplier

  validates :account_number, presence: true
  validate :account_digit_valid?

  private
  def account_digit_valid?
    d = AccountsHelper::CheckAccountDigit.new(account_number, digit)
    errors.add(:digit, 'invalido! verificar o numero.') if d.check_digit?
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]
  before_action :set_supplier_id_options, only: %i[new show edit update destroy]

  def index
    @accounts = Account.all
  end

  def show; end

  def new
    @account = Account.new
  end

  def edit; end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to account_url(@account), notice: 'Account was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @account.update(account_params)
      redirect_to account_url(@account), notice: 'Account was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private

  def set_supplier_id_options
    @supplier_id_options = Supplier.all.pluck(:name, :id)
  end

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:account_number, :supplier_id, :digit)
  end
end

app/controllers/api/accounts_controller.rb
# frozen_string_literal: true

module Api
  class AccountsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_account

    def index
      @accounts = Account.includes(:supplier).all
      render json: @accounts
    end

    def show
      render json: @account
    end

    def create
      @account = Account.new(params_account)
      if @account.save
        render json: @account, status: :created
      else
        render json: @account.errors, status: :unprocessable_entity
      end
    end

    def update
      if @account.update(params_account)
        render json: @account, except: %i[created_at]
      else
        render json: @account.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @account.destroy
      head :no_content
    end

    private

    def set_account
      @account = Account.find_by(id: params[:id])
    end

    def params_account
      params.require(:account).permit(:account_number, :digit, :supplier_id)
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  class CheckAccountDigit
    def initialize(account, digit)
      @account = account
      @digit = digit
    end

    def check_digit?
      i = @account.length() + 1
      j = 0
      sum_product = 0
      while i > 1
        sum_product += @account[j].to_i * i
        i -= 1
        j += 1
      end

      sum_product = (sum_product * 10)
      digit = sum_product % 11
      @digit.to_s == digit.to_s
    end
  end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Account number:</strong>
    <%= account.account_number %>
  </p>

  <p>
    <strong>Digit:</strong>
    <%= account.digit %>
  </p>

  <p>
    <strong>Supplier:</strong>
    <%= account.supplier.name %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :account_number, style: "display: block" %>
    <%= form.text_field :account_number %>
  </div>

  <div>
    <%= form.label :digit, style: "display: block" %>
    <%= form.text_field :digit %>
  </div>

  <div class="field">
    <%= form.label :supplier_id, style: "display: block" %>
    <%= form.select("supplier_id", @supplier_id_options, include_blank: true)%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
  <% end %>
</div>

<p>
  <%= link_to "New account", new_account_path %>
</p>

<p>
  <%= link_to "Page home", root_path %>
</p>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>